sonar.projectKey=MatheeshaDias0926_notification-service
sonar.organization=matheeshadias0926
sonar.projectName=Notification Service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**
